# Generated by Django 5.0.6 on 2024-07-03 03:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('box', '0005_specialroutine_selecteduser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='selecteduser',
            name='routine',
        ),
        migrations.RemoveField(
            model_name='selecteduser',
            name='user',
        ),
        migrations.DeleteModel(
            name='SpecialRoutine',
        ),
        migrations.DeleteModel(
            name='SelectedUser',
        ),
    ]
