# Generated by Django 5.0.6 on 2024-07-03 03:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('box', '0006_remove_selecteduser_routine_remove_selecteduser_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecialRoutine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('authorized_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authorized_routines', to='auth.group')),
            ],
        ),
    ]
