# Generated by Django 5.0.6 on 2024-07-03 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('box', '0007_specialroutine'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specialroutine',
            name='authorized_group',
        ),
        migrations.AddField(
            model_name='specialroutine',
            name='visible_to_groups',
            field=models.ManyToManyField(blank=True, to='auth.group', verbose_name='Grupos autorizados'),
        ),
    ]
