# Generated by Django 5.0.6 on 2024-07-03 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('box', '0008_remove_specialroutine_authorized_group_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialroutine',
            name='visible_to_groups',
            field=models.ManyToManyField(blank=True, to='auth.group'),
        ),
    ]
