# Generated by Django 5.0.6 on 2024-07-09 15:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('box', '0009_alter_specialroutine_visible_to_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialroutine',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
