# Generated by Django 5.0.6 on 2024-05-15 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miembros', '0004_formulariocontacto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formulariocontacto',
            name='profesor',
            field=models.CharField(choices=[('Consulta general', 'Consulta general'), ('Soporte técnico', 'Soporte técnico'), ('Información de productos', 'Información de productos'), ('Otros', 'Otros')], max_length=100),
        ),
        migrations.AlterField(
            model_name='formulariocontacto',
            name='tipo_consulta',
            field=models.CharField(choices=[('Consult general', 'Consulta general'), ('Soporte écnico', 'Soporte técnico'), ('Informació de productos', 'Información de productos'), ('Otro', 'Otros')], max_length=100),
        ),
    ]
