# Generated by Django 5.0.6 on 2024-05-20 00:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miembros', '0005_alter_formulariocontacto_profesor_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='formulariocontacto',
            name='profesor',
            field=models.CharField(choices=[('crossfit', 'crossfit'), ('funcional kid', 'funcional kid'), ('jiu jitsu', 'jiu jitsu'), ('Otros', 'Otros')], max_length=100),
        ),
        migrations.AlterField(
            model_name='formulariocontacto',
            name='tipo_consulta',
            field=models.CharField(choices=[('horarios', 'horarios'), ('profesores', 'profesores'), ('felicitarnos', 'felicitarnos'), ('critica constructiva', 'critica constructiva')], max_length=100),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='usuario/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
