# Generated by Django 5.0.6 on 2024-05-24 03:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('miembros', '0008_userprofile_bio_userprofile_birth_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='location',
            new_name='localidad',
        ),
    ]
