# Generated by Django 5.0.6 on 2024-06-17 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miembros', '0012_alter_userprofile_profile_image_cuota'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuota',
            name='pagada',
            field=models.BooleanField(default=False),
        ),
    ]
