# Generated by Django 5.0.6 on 2024-07-05 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('miembros', '0016_disciplina'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Disciplina',
        ),
    ]
